// AUTO-GENERATED by tools/gen_dashboard_fonts.sh from tools/dashboard_fonts_manifest.txt.
// Do not hand-edit - edit the manifest and rerun the script instead.
#pragma once

#include <lvgl.h>

extern const lv_font_t font_plexmono_hero_240;
extern const lv_font_t font_plexmono_deg_128;
extern const lv_font_t font_plexmono_clock_20;
extern const lv_font_t font_plexmono_metricvalue_26;
extern const lv_font_t font_plexmono_hourtemp_20;
extern const lv_font_t font_plexmono_hilo_18;
extern const lv_font_t font_plexmono_feels_16;
extern const lv_font_t font_plexmono_statusright_13;
extern const lv_font_t font_plexmono_dayrange_16;
extern const lv_font_t font_plexmono_region_20;
extern const lv_font_t font_plexmono_dailypop_11;
extern const lv_font_t font_plexmono_metricspan_14;
extern const lv_font_t font_plexmono_title_11;
extern const lv_font_t font_plexmono_expand_22;
extern const lv_font_t font_plexmono_hourlytitle_16;
extern const lv_font_t font_plexmono_hourclock_16;
extern const lv_font_t font_plexmono_dailytitle_22;
extern const lv_font_t font_plexmono_metriclabel_12;
extern const lv_font_t font_plexmono_hourpop_14;
extern const lv_font_t font_archivo_condition_26;
extern const lv_font_t font_archivo_statusname_20;
extern const lv_font_t font_archivo_dayname_14;
extern const lv_font_t font_plexmono_backbtn_16;
extern const lv_font_t font_archivo_hdtitle_26;
extern const lv_font_t font_plexmono_hdsub_18;
extern const lv_font_t font_plexmono_legend_14;
extern const lv_font_t font_plexmono_hcardtime_14;
extern const lv_font_t font_plexmono_hcardtemp_26;
extern const lv_font_t font_plexmono_hcardpop_18;
extern const lv_font_t font_plexmono_headcol_14;
extern const lv_font_t font_plexmono_dailydate_16;
extern const lv_font_t font_archivo_dailydesc_18;
extern const lv_font_t font_plexmono_segtemp_20;
extern const lv_font_t font_plexmono_segpop_16;
extern const lv_font_t font_plexmono_sunbar_16;

