// AUTO-GENERATED by tools/gen_dashboard_icons.sh from tools/dashboard_icons_manifest.txt.
// Do not hand-edit - edit the manifest and rerun the script instead.
#pragma once

#include <lvgl.h>

extern const lv_image_dsc_t sun_hero;
extern const lv_image_dsc_t sun_dayrow;
extern const lv_image_dsc_t sun_hcard;
extern const lv_image_dsc_t mostly_clear_hero;
extern const lv_image_dsc_t mostly_clear_dayrow;
extern const lv_image_dsc_t mostly_clear_hcard;
extern const lv_image_dsc_t partly_cloudy_hero;
extern const lv_image_dsc_t partly_cloudy_dayrow;
extern const lv_image_dsc_t partly_cloudy_hcard;
extern const lv_image_dsc_t cloud_hero;
extern const lv_image_dsc_t cloud_dayrow;
extern const lv_image_dsc_t cloud_hcard;
extern const lv_image_dsc_t night_cloudy_hero;
extern const lv_image_dsc_t night_cloudy_dayrow;
extern const lv_image_dsc_t night_cloudy_hcard;
extern const lv_image_dsc_t windy_hero;
extern const lv_image_dsc_t windy_dayrow;
extern const lv_image_dsc_t windy_hcard;
extern const lv_image_dsc_t light_rain_hero;
extern const lv_image_dsc_t light_rain_dayrow;
extern const lv_image_dsc_t light_rain_hcard;
extern const lv_image_dsc_t rain_hero;
extern const lv_image_dsc_t rain_dayrow;
extern const lv_image_dsc_t rain_hcard;
extern const lv_image_dsc_t heavy_rain_hero;
extern const lv_image_dsc_t heavy_rain_dayrow;
extern const lv_image_dsc_t heavy_rain_hcard;
extern const lv_image_dsc_t snow_hero;
extern const lv_image_dsc_t snow_dayrow;
extern const lv_image_dsc_t snow_hcard;
extern const lv_image_dsc_t sleet_hero;
extern const lv_image_dsc_t sleet_dayrow;
extern const lv_image_dsc_t sleet_hcard;
extern const lv_image_dsc_t hail_hero;
extern const lv_image_dsc_t hail_dayrow;
extern const lv_image_dsc_t hail_hcard;
extern const lv_image_dsc_t thunderstorm_hero;
extern const lv_image_dsc_t thunderstorm_dayrow;
extern const lv_image_dsc_t thunderstorm_hcard;
extern const lv_image_dsc_t fog_hero;
extern const lv_image_dsc_t fog_dayrow;
extern const lv_image_dsc_t fog_hcard;
extern const lv_image_dsc_t moon_hero;
extern const lv_image_dsc_t moon_dayrow;
extern const lv_image_dsc_t moon_hcard;

