// AUTO-GENERATED by tools/gen_font_gallery.sh from tools/font_gallery_manifest.txt.
// Do not hand-edit - edit the manifest and rerun the script instead.
#pragma once

#include <font_gallery.h>

extern const lv_font_t font_archivo_48;
extern const lv_font_t font_archivo_64;
extern const lv_font_t font_archivo_80;
extern const lv_font_t font_archivo_96;
extern const lv_font_t font_archivo_108;
extern const lv_font_t font_archivo_128;
extern const lv_font_t font_archivo_160;
extern const lv_font_t font_archivo_192;
extern const lv_font_t font_archivo_256;
extern const lv_font_t font_archivo_384;
extern const lv_font_t font_archivo_512;

static constexpr FontGalleryEntry kFontGalleryEntries[] = {
    {&font_archivo_48, "Archivo 48px (current LVGL built-in ceiling)"},
    {&font_archivo_64, "Archivo 64px"},
    {&font_archivo_80, "Archivo 80px"},
    {&font_archivo_96, "Archivo 96px"},
    {&font_archivo_108, "Archivo 108px (dashboard.html hero size)"},
    {&font_archivo_128, "Archivo 128px"},
    {&font_archivo_160, "Archivo 160px"},
    {&font_archivo_192, "Archivo 192px"},
    {&font_archivo_256, "Archivo 256px"},
    {&font_archivo_384, "Archivo 384px"},
    {&font_archivo_512, "Archivo 512px (taller than the 720px panel)"},

};

static constexpr size_t kFontGalleryEntryCount = sizeof(kFontGalleryEntries) / sizeof(kFontGalleryEntries[0]);
