#!/usr/bin/env bash
# Generates the production weather-condition icons for the Dashboard
# screen (src/dashboard_ui.cpp) from tools/dashboard_icons_manifest.txt.
# Not run by the firmware build itself - run this by hand whenever the
# manifest or a source SVG changes.
#
# Two-stage pipeline: rsvg-convert rasterizes each source SVG to a PNG at
# the manifest's size_px, then tools/png_to_lvgl_image.py converts that
# PNG into an LVGL v9 lv_image_dsc_t C source file (see that script's own
# header comment for why this is a hand-rolled converter instead of
# LVGL's own lv_img_conv tool - the published npm version predates v9's
# image header format).
#
# Requires: rsvg-convert (brew install librsvg) and Pillow
# (pip3 install Pillow).
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

MANIFEST="tools/dashboard_icons_manifest.txt"
OUT_DIR="src/dashboard_icons"
HEADER_OUT="include/dashboard_icons.h"
PNG_CACHE_DIR="$(mktemp -d -t dashboard_icons_png_cache)"

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/*.c "$HEADER_OUT"
trap 'rm -rf "$PNG_CACHE_DIR"' EXIT

externs=""

while IFS='|' read -r name source size; do
  [[ -z "$name" || "$name" == \#* ]] && continue

  echo "generating ${name} (${size}px from $(basename "$source"))..."

  png="$PNG_CACHE_DIR/${name}.png"
  rsvg-convert -w "$size" -h "$size" "$source" -o "$png"
  python3 tools/png_to_lvgl_image.py "$png" -o "$OUT_DIR/${name}.c" -n "$name"

  externs="${externs}extern const lv_image_dsc_t ${name};\n"
done <"$MANIFEST"

{
  echo "// AUTO-GENERATED by tools/gen_dashboard_icons.sh from tools/dashboard_icons_manifest.txt."
  echo "// Do not hand-edit - edit the manifest and rerun the script instead."
  echo "#pragma once"
  echo
  echo "#include <lvgl.h>"
  echo
  echo -e "$externs"
} >"$HEADER_OUT"

echo "done. Generated ${HEADER_OUT} and $(find "$OUT_DIR" -name '*.c' | wc -l | tr -d ' ') icon source(s)."
