#!/usr/bin/env bash
# Regenerates every font in tools/font_test_manifest.txt for the
# src/font_size_test.cpp example (see [env:font-test] in platformio.ini).
# Not part of the firmware build itself - run this by hand whenever the
# manifest changes. To test a different family/size/subset, edit the
# manifest and rerun this script; nothing in font_size_test.cpp needs to
# change, it's driven entirely by the generated manifest header below.
#
# lv_font_conv (via npx, no global install needed) can't read .woff2
# sources directly - it wants ttf/otf - so each distinct .woff2 in the
# manifest is converted to a temp .ttf once (cached, not once per line)
# with fonttools. Requires: `pip3 install fonttools brotli` (brotli is
# what makes fonttools able to decode woff2) and `npx` (ships with
# node/npm).
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

MANIFEST="tools/font_test_manifest.txt"
OUT_DIR="src/fonts_test"
HEADER_OUT="include/fonts_test_manifest.h"
TTF_CACHE_DIR="$(mktemp -d -t font_test_ttf_cache)"

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/*.c "$HEADER_OUT"
trap 'rm -rf "$TTF_CACHE_DIR"' EXIT

# Returns a .ttf path for a manifest source, converting+caching once per
# distinct .woff2 path (macOS ships bash 3.2, no associative arrays, so
# the cache is just a directory keyed by sanitized source path rather
# than an in-memory map). .ttf/.otf sources pass through unchanged.
ttf_for() {
  local source="$1"
  case "$source" in
    *.ttf | *.otf)
      echo "$source"
      return
      ;;
  esac

  local key cached
  key="$(echo "$source" | tr '/.' '__')"
  cached="$TTF_CACHE_DIR/${key}.ttf"
  if [[ ! -f "$cached" ]]; then
    python3 -c "
from fontTools.ttLib import TTFont
f = TTFont('$source')
f.flavor = None
f.save('$cached')
"
  fi
  echo "$cached"
}

externs=""
entries=""

while IFS='|' read -r name source size symbols caption; do
  [[ -z "$name" || "$name" == \#* ]] && continue

  ttf="$(ttf_for "$source")"
  echo "generating ${name} (${size}px from $(basename "$source"))..."

  # --no-compress: lv_font_conv RLE-compresses glyph bitmaps by default,
  # which needs LV_USE_FONT_COMPRESSED enabled to decode - this project's
  # lv_conf.h never turns that on for the real firmware, and compressed
  # glyphs silently failed to render when tested (confirmed on hardware:
  # blank/garbled output). Uncompressed costs more flash, acceptable for
  # a throwaway subset used to answer a legibility question, not shipped.
  npx --yes lv_font_conv \
    --font "$ttf" \
    --size "$size" \
    --bpp 4 \
    --format lvgl \
    --symbols "$symbols" \
    --no-compress \
    --lv-font-name "$name" \
    -o "$OUT_DIR/${name}.c"

  externs="${externs}extern const lv_font_t ${name};\n"
  entries="${entries}    {&${name}, \"${caption}\"},\n"
done <"$MANIFEST"

{
  echo "// AUTO-GENERATED by tools/gen_test_fonts.sh from tools/font_test_manifest.txt."
  echo "// Do not hand-edit - edit the manifest and rerun the script instead."
  echo "#pragma once"
  echo
  echo "#include \"fonts_test.h\""
  echo
  echo -e "$externs"
  echo "static constexpr FontTestEntry kFontTestEntries[] = {"
  echo -e "$entries"
  echo "};"
  echo
  echo "static constexpr size_t kFontTestEntryCount = sizeof(kFontTestEntries) / sizeof(kFontTestEntries[0]);"
} >"$HEADER_OUT"

echo "done. Generated ${HEADER_OUT} and $(find "$OUT_DIR" -name '*.c' | wc -l | tr -d ' ') font source(s)."
