#!/usr/bin/env bash
# Generates the production fonts for the Dashboard screen
# (src/dashboard_ui.cpp) from tools/dashboard_fonts_manifest.txt. Not run
# by the firmware build itself - run this by hand whenever the manifest
# changes.
#
# Deliberately separate from tools/gen_font_gallery.sh /
# lib/font_gallery: those are a dev/test tool (pick-a-size-by-eye, any
# font, no production dependency on it); this generates the actual fonts
# src/dashboard_ui.cpp links against, with no FontGalleryEntry/sample/
# caption machinery - just extern const lv_font_t declarations.
#
# lv_font_conv (via npx, no global install needed) can't read .woff2
# sources directly - it wants ttf/otf - so each distinct .woff2 in the
# manifest is converted to a temp .ttf once (cached, not once per line)
# with fonttools. Requires: `pip3 install fonttools brotli` (brotli is
# what makes fonttools able to decode woff2) and `npx` (ships with
# node/npm).
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

MANIFEST="tools/dashboard_fonts_manifest.txt"
OUT_DIR="src/dashboard_fonts"
HEADER_OUT="include/dashboard_fonts.h"
TTF_CACHE_DIR="$(mktemp -d -t dashboard_fonts_ttf_cache)"

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/*.c "$HEADER_OUT"
trap 'rm -rf "$TTF_CACHE_DIR"' EXIT

# Returns a .ttf path for a manifest source, converting+caching once per
# distinct .woff2 path (macOS ships bash 3.2, no associative arrays, so
# the cache is just a directory keyed by sanitized source path rather
# than an in-memory map). .ttf/.otf sources pass through unchanged.
ttf_for() {
  local source="$1"
  case "$source" in
    *.ttf | *.otf)
      echo "$source"
      return
      ;;
  esac

  local key cached
  key="$(echo "$source" | tr '/.' '__')"
  cached="$TTF_CACHE_DIR/${key}.ttf"
  if [[ ! -f "$cached" ]]; then
    python3 -c "
from fontTools.ttLib import TTFont
f = TTFont('$source')
f.flavor = None
f.save('$cached')
"
  fi
  echo "$cached"
}

externs=""

while IFS='|' read -r name source size symbols compress; do
  [[ -z "$name" || "$name" == \#* ]] && continue

  ttf="$(ttf_for "$source")"
  compress_flag="--no-compress"
  compress_note="uncompressed"
  if [[ "$compress" == "1" ]]; then
    compress_flag=""
    compress_note="compressed (LV_USE_FONT_COMPRESSED)"
  fi
  echo "generating ${name} (${size}px from $(basename "$source"), ${compress_note})..."

  # shellcheck disable=SC2086
  npx --yes lv_font_conv \
    --font "$ttf" \
    --size "$size" \
    --bpp 4 \
    --format lvgl \
    --symbols "$symbols" \
    $compress_flag \
    --lv-font-name "$name" \
    -o "$OUT_DIR/${name}.c"

  externs="${externs}extern const lv_font_t ${name};\n"
done <"$MANIFEST"

{
  echo "// AUTO-GENERATED by tools/gen_dashboard_fonts.sh from tools/dashboard_fonts_manifest.txt."
  echo "// Do not hand-edit - edit the manifest and rerun the script instead."
  echo "#pragma once"
  echo
  echo "#include <lvgl.h>"
  echo
  echo -e "$externs"
} >"$HEADER_OUT"

echo "done. Generated ${HEADER_OUT} and $(find "$OUT_DIR" -name '*.c' | wc -l | tr -d ' ') font source(s)."
