#!/usr/bin/env python3
"""Converts a PNG into an LVGL v9 `lv_image_dsc_t` C source file.

Not using LVGL's own `lv_img_conv` npm tool (the one `gen_dashboard_fonts.sh`'s
sibling would reach for): confirmed by reading its source
(lib/convert.ts) that it still emits LVGL v8's old packed-uint32 image
header (`cf | w<<10 | h<<21`) - the last published version, 0.4.0, predates
LVGL v9's `lv_image_header_t` struct layout (magic/cf/flags/w/h/stride as
real struct fields, not packed bits - see
.pio/libdeps/tab5/lvgl/src/draw/lv_image_dsc.h). Its output doesn't compile
as a valid v9 `lv_image_dsc_t` initializer, so this project hand-rolls the
much smaller conversion instead, matching v9's real struct exactly.

Output format: LV_COLOR_FORMAT_ARGB8888 (uncompressed, 4 bytes/pixel,
byte order blue/green/red/alpha - confirmed from lv_color32_t's field
order in lv_color.h). Icons here are small (<=130px) and few (8 total),
so the flash cost of skipping RGB565A8/compression entirely is
negligible against the ~6.25MB OTA budget, and ARGB8888 is the format
least likely to have a subtle packing bug in a from-scratch converter.
"""
import argparse
import sys

try:
    from PIL import Image
except ImportError:
    print("error: Pillow is required (pip3 install Pillow)", file=sys.stderr)
    sys.exit(1)

LV_IMAGE_HEADER_MAGIC = 0x19
LV_COLOR_FORMAT_ARGB8888 = 0x10


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_png")
    parser.add_argument("-o", "--output", required=True, help="output .c file path")
    parser.add_argument("-n", "--name", required=True, help="C identifier for the generated lv_image_dsc_t")
    args = parser.parse_args()

    img = Image.open(args.input_png).convert("RGBA")
    width, height = img.size
    stride = width * 4  # ARGB8888, no row padding needed.

    pixel_bytes = bytearray(width * height * 4)
    pixels = img.load()
    i = 0
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            # blue, green, red, alpha - lv_color32_t's field order.
            pixel_bytes[i] = b
            pixel_bytes[i + 1] = g
            pixel_bytes[i + 2] = r
            pixel_bytes[i + 3] = a
            i += 4

    hex_bytes = ", ".join(f"0x{b:02x}" for b in pixel_bytes)

    with open(args.output, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_dashboard_icons.sh (tools/png_to_lvgl_image.py) from\n")
        f.write("// tools/dashboard_icons_manifest.txt. Do not hand-edit - edit the manifest/source SVG\n")
        f.write("// and rerun the script instead.\n")
        f.write("#include <lvgl.h>\n\n")
        f.write(f"static const uint8_t {args.name}_map[] = {{\n  {hex_bytes}\n}};\n\n")
        f.write(f"const lv_image_dsc_t {args.name} = {{\n")
        f.write("  .header = {\n")
        f.write(f"    .magic = {LV_IMAGE_HEADER_MAGIC},\n")
        f.write(f"    .cf = {LV_COLOR_FORMAT_ARGB8888},\n")
        f.write("    .flags = 0,\n")
        f.write(f"    .w = {width},\n")
        f.write(f"    .h = {height},\n")
        f.write(f"    .stride = {stride},\n")
        f.write("    .reserved_2 = 0,\n")
        f.write("  },\n")
        f.write(f"  .data_size = sizeof({args.name}_map),\n")
        f.write(f"  .data = {args.name}_map,\n")
        f.write("  .reserved = NULL,\n")
        f.write("  .reserved_2 = NULL,\n")
        f.write("};\n")

    print(f"wrote {args.output} ({width}x{height}, {len(pixel_bytes)} bytes)")


if __name__ == "__main__":
    main()
