#include "dashboard_ui.h"

#include <lvgl.h>
#include <time.h>

#include "dashboard_fonts.h"
#include "dashboard_icon_lookup.h"
#include "dashboard_icons.h"
#include "daily_forecast_ui.h"
#include "date_utils.h"
#include "hourly_detail_ui.h"
#include "logging.h"
#include "weather_icon.h"

// The Dashboard screen (docs/mockups/dashboard.html), Phase 1: statusbar,
// current conditions + hi/lo + 4-metric grid, 7-day outlook, 8-hour strip.
// Weather condition glyphs (hero + 7-day rows) render the 4-icon
// vocabulary the mockups actually define (sun/cloud/rain/moon - see
// weather_icon.h), generated by tools/gen_dashboard_icons.sh; static
// images today, architected so a future animated variant is a localized
// widget swap (lv_image_create -> lv_animimg_create), not a rewrite - see
// docs/rendering.md's Icons section. Tapping the Hourly section pushes to
// hourly_detail_ui.cpp (see buildHourlyRow()); the 7-Day Outlook has no
// tap target yet, that detail screen doesn't exist. No Day/Night toggle
// (this kiosk always runs the dark palette, same as every other screen
// in this firmware).
//
// Every padding/gap/size below is the mockup's own raw px value, used
// as-is - not scaled. docs/mockups/dashboard.html's `.device` frame is
// already built at exactly 1280x720, the panel's own native resolution,
// so its CSS px are already real device px by construction. An earlier
// version of this file multiplied every value by ~2.9x on the theory
// that the panel's pixel density needed compensating for (the right call
// for the *status/provisioning* screens, whose sizes were picked
// freehand with no mockup reference - see docs/rendering.md) - wrong
// here, and confirmed wrong on hardware: the whole layout overflowed its
// 720px height badly (hero digit alone at 312px). See
// tools/dashboard_fonts_manifest.txt for the same correction on the font
// side.
//
// Unlike showStatusScreen() (boot_ui.cpp), which rebuilds from scratch on
// every call - fine for a rare, simple screen - this screen is built once
// (module-level static lv_obj_t* for everything that changes) and updated
// in place on every subsequent call, matching the mockup's own stated
// on-device goal ("redrawn only where data changed (partial DMA flush)").
// Same static-widget-pointer convention provisioning.cpp already uses for
// its net-card/step-list.
namespace {

// Dark-theme palette, docs/mockups/assets/style.css's --ink/--sub/etc.
// Only the dark values: this kiosk never runs the light theme.
constexpr uint32_t kInk = 0xF0E9D8;
constexpr uint32_t kSub = 0xA89E8C;
constexpr uint32_t kPaper = 0x121417;
constexpr uint32_t kPanel = 0x1B1E22;
constexpr uint32_t kLine = 0x2A2E33;  // Same solid approximation of --line
                                      // provisioning.cpp's net-card border
                                      // already uses.
constexpr uint32_t kLineStrong = 0x3A3F45;  // mockup's --line-strong, matches
                                             // hourly_detail_ui.cpp's back
                                             // button border - "Expand" is
                                             // styled the same way.
constexpr uint32_t kBrass = 0xD99A4E;
constexpr uint32_t kBrassStrong = 0xE9B06C;
constexpr uint32_t kTeal = 0x6FB3AC;
constexpr uint32_t kEmber = 0xE2794E;

constexpr size_t kMaxDayRows = kMaxDailyPoints;
// 8, not kMaxHourlyPoints (16) - the compact strip's layout/sizing was
// built for 8 columns (see buildHourlyRow()) and stays that way even
// though kMaxHourlyPoints grew to 16 for hourly_detail_ui.cpp's fuller
// view. Decoupled on purpose: this cell count and the fetch depth are
// two different concerns now.
constexpr size_t kMaxHourCells = 8;

struct DayRowWidgets {
  lv_obj_t *row = nullptr;
  lv_obj_t *name = nullptr;
  lv_obj_t *icon = nullptr;
  lv_obj_t *lo = nullptr;
  lv_obj_t *track = nullptr;
  lv_obj_t *fill = nullptr;
  lv_obj_t *hi = nullptr;
  lv_obj_t *pop = nullptr;
};


struct HourCellWidgets {
  lv_obj_t *cell = nullptr;
  lv_obj_t *t = nullptr;
  lv_obj_t *barWrap = nullptr;
  lv_obj_t *bar = nullptr;
  lv_obj_t *temp = nullptr;
  lv_obj_t *pop = nullptr;
};

lv_obj_t *g_screen = nullptr;
// Cached so the Hourly title row's click handler (buildHourlyRow()) has
// data to hand off to showHourlyDetailScreen() - it fires from an LVGL
// event callback, not from showDashboardScreen()'s own call site, so it
// can't rely on a parameter passed there.
SharedState::DashboardSnapshot g_lastSnapshot;
lv_obj_t *g_nameLabel = nullptr;
lv_obj_t *g_regionLabel = nullptr;
lv_obj_t *g_syncDot = nullptr;
lv_obj_t *g_syncLabel = nullptr;
lv_obj_t *g_clockLabel = nullptr;

lv_obj_t *g_tempLabel = nullptr;
lv_obj_t *g_degLabel = nullptr;
lv_obj_t *g_conditionIcon = nullptr;
lv_obj_t *g_conditionLabel = nullptr;
lv_obj_t *g_feelsLabel = nullptr;
lv_obj_t *g_hiLabel = nullptr;
lv_obj_t *g_loLabel = nullptr;

// Humidity, Wind, UV Index, Precip, in that order (matches the mockup).
lv_obj_t *g_metricValueLabels[4] = {nullptr, nullptr, nullptr, nullptr};
lv_obj_t *g_metricSpanLabels[4] = {nullptr, nullptr, nullptr, nullptr};

DayRowWidgets g_dayRows[kMaxDayRows];
HourCellWidgets g_hourCells[kMaxHourCells];

lv_obj_t *makeLabel(lv_obj_t *parent, uint32_t colorArgb, const lv_font_t *font) {
  lv_obj_t *label = lv_label_create(parent);
  lv_obj_set_style_text_color(label, lv_color_hex(colorArgb), 0);
  lv_obj_set_style_text_font(label, font, 0);
  return label;
}

lv_obj_t *makeRow(lv_obj_t *parent) {
  lv_obj_t *row = lv_obj_create(parent);
  lv_obj_set_size(row, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(row, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(row, 0, 0);
  lv_obj_set_style_pad_all(row, 0, 0);
  lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
  lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);
  return row;
}

lv_obj_t *makeColumn(lv_obj_t *parent) {
  lv_obj_t *col = lv_obj_create(parent);
  lv_obj_set_size(col, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(col, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(col, 0, 0);
  lv_obj_set_style_pad_all(col, 0, 0);
  lv_obj_set_flex_flow(col, LV_FLEX_FLOW_COLUMN);
  lv_obj_clear_flag(col, LV_OBJ_FLAG_SCROLLABLE);
  return col;
}

// Animated press feedback for a clickable pill button: on LV_STATE_PRESSED
// the border brightens and a faint brass tint fades in, then reverses on
// release - lv_style_transition_dsc_t makes LVGL animate both directions
// automatically, no extra event callbacks needed. Duplicated in
// hourly_detail_ui.cpp (same per-screen-file convention as makeLabel/
// makeRow/makeColumn - no shared UI-kit yet).
void addPressFeedback(lv_obj_t *btn) {
  static const lv_style_prop_t kProps[] = {LV_STYLE_BG_OPA, LV_STYLE_BG_COLOR, LV_STYLE_BORDER_COLOR,
                                            LV_STYLE_PROP_INV};
  static lv_style_transition_dsc_t kTransition;
  lv_style_transition_dsc_init(&kTransition, kProps, lv_anim_path_ease_out, 120, 0, nullptr);
  lv_obj_set_style_transition(btn, &kTransition, LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(btn, lv_color_hex(kBrass), LV_STATE_PRESSED);
  lv_obj_set_style_bg_opa(btn, LV_OPA_30, LV_STATE_PRESSED);
  lv_obj_set_style_border_color(btn, lv_color_hex(kBrassStrong), LV_STATE_PRESSED);
}

// ---------------------------------------------------------------------
// Statusbar: location name/region (left), sync status + clock (right).
// Mockup: .statusbar { padding: 18px 30px 12px }, .loc gap 10, .right
// gap 22, .sync gap 7, dot 6px.
// ---------------------------------------------------------------------

lv_obj_t *buildStatusbar(lv_obj_t *parent) {
  lv_obj_t *bar = lv_obj_create(parent);
  lv_obj_set_size(bar, LV_PCT(100), LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(bar, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(bar, 0, 0);
  lv_obj_set_style_pad_hor(bar, 30, 0);
  lv_obj_set_style_pad_top(bar, 18, 0);
  lv_obj_set_style_pad_bottom(bar, 12, 0);
  lv_obj_set_flex_flow(bar, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(bar, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(bar, LV_OBJ_FLAG_SCROLLABLE);

  lv_obj_t *loc = makeRow(bar);
  lv_obj_set_style_pad_column(loc, 10, 0);
  lv_obj_set_flex_align(loc, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
  g_nameLabel = makeLabel(loc, kInk, &font_archivo_statusname_20);
  g_regionLabel = makeLabel(loc, kSub, &font_plexmono_region_20);

  lv_obj_t *right = makeRow(bar);
  lv_obj_set_style_pad_column(right, 22, 0);
  lv_obj_set_flex_align(right, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

  lv_obj_t *sync = makeRow(right);
  lv_obj_set_style_pad_column(sync, 7, 0);
  lv_obj_set_flex_align(sync, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  g_syncDot = lv_obj_create(sync);
  lv_obj_set_size(g_syncDot, 6, 6);
  lv_obj_set_style_radius(g_syncDot, LV_RADIUS_CIRCLE, 0);
  lv_obj_set_style_bg_color(g_syncDot, lv_color_hex(kTeal), 0);
  lv_obj_set_style_bg_opa(g_syncDot, LV_OPA_COVER, 0);
  lv_obj_set_style_border_width(g_syncDot, 0, 0);
  lv_obj_clear_flag(g_syncDot, LV_OBJ_FLAG_SCROLLABLE);
  g_syncLabel = makeLabel(sync, kSub, &font_plexmono_statusright_13);

  g_clockLabel = makeLabel(right, kInk, &font_plexmono_clock_20);

  return bar;
}

// ---------------------------------------------------------------------
// Primary column: current reading + hi/lo + 4-metric grid.
// Mockup: .primary { padding: 22px 30px 18px }, .reading gap 2, .hilo
// gap 22 / margin-top 4, .metrics gap 1, .metric { padding: 12px 14px },
// value/span gap implicit (inline flex, no explicit gap in mockup).
// ---------------------------------------------------------------------

lv_obj_t *buildMetricCell(lv_obj_t *parent, const char *label, size_t index) {
  lv_obj_t *cell = makeColumn(parent);
  lv_obj_set_style_bg_color(cell, lv_color_hex(kPanel), 0);
  lv_obj_set_style_bg_opa(cell, LV_OPA_COVER, 0);
  lv_obj_set_style_pad_hor(cell, 18, 0);
  lv_obj_set_style_pad_ver(cell, 16, 0);
  lv_obj_set_style_pad_row(cell, 8, 0);
  lv_obj_set_width(cell, LV_PCT(100));

  makeLabel(cell, kSub, &font_plexmono_metriclabel_12);
  lv_label_set_text(lv_obj_get_child(cell, -1), label);

  lv_obj_t *valueRow = makeRow(cell);
  // Full cell width, not content-sized: END on the main axis only
  // right-aligns within whatever free space actually exists, and a
  // content-sized row has none.
  lv_obj_set_width(valueRow, LV_PCT(100));
  lv_obj_set_flex_align(valueRow, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
  g_metricValueLabels[index] = makeLabel(valueRow, kInk, &font_plexmono_metricvalue_26);
  g_metricSpanLabels[index] = makeLabel(valueRow, kSub, &font_plexmono_metricspan_14);

  return cell;
}

lv_obj_t *buildPrimaryColumn(lv_obj_t *parent) {
  lv_obj_t *col = makeColumn(parent);
  lv_obj_set_height(col, LV_PCT(100));
  lv_obj_set_flex_grow(col, 155);
  lv_obj_set_flex_align(col, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_set_style_pad_hor(col, 30, 0);
  lv_obj_set_style_pad_top(col, 22, 0);
  lv_obj_set_style_pad_bottom(col, 18, 0);
  lv_obj_set_style_border_side(col, LV_BORDER_SIDE_RIGHT, 0);
  lv_obj_set_style_border_color(col, lv_color_hex(kLine), 0);
  lv_obj_set_style_border_width(col, 1, 0);

  // Hero temp fills the left side; glyph-less info column (condition,
  // feels-like, hi/lo - no icon, still out of scope per the "skip icons
  // in Phase 1" decision) sits right-aligned on the right, replacing the
  // earlier full-width-stacked layout where hi/lo was its own row below
  // everything.
  lv_obj_t *top = makeColumn(col);
  lv_obj_set_width(top, LV_PCT(100));

  lv_obj_t *nowRow = makeRow(top);
  lv_obj_set_width(nowRow, LV_PCT(100));
  lv_obj_set_flex_align(nowRow, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

  lv_obj_t *tempBlock = makeRow(nowRow);
  lv_obj_set_flex_align(tempBlock, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  g_tempLabel = makeLabel(tempBlock, kInk, &font_plexmono_hero_240);
  g_degLabel = makeLabel(tempBlock, kBrassStrong, &font_plexmono_deg_128);

  lv_obj_t *infoBlock = makeColumn(nowRow);
  lv_obj_set_style_pad_row(infoBlock, 8, 0);
  lv_obj_set_flex_align(infoBlock, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
  // Fixed width, not LV_SIZE_CONTENT + max_width - g_conditionLabel below
  // is set to LV_PCT(100) of this column, so a content-sized width here
  // would be circular (infoBlock sizing off its child, that child sizing
  // off infoBlock) the same way the earlier mainRow bug was; confirmed on
  // hardware, it pushed the glyph placeholder out of bounds. 210px is
  // whatever's left once the hero temp claims its worst case width (3
  // digits, e.g. "104", at font_plexmono_hero_240's 144px/digit advance +
  // the deg suffix's ~77px) out of the primary column's ~718px content
  // width (778px flex-grow share minus its own 30px*2 horizontal
  // padding).
  lv_obj_set_width(infoBlock, 210);

  // 130px, not 105px - filling more of the space freed up once hi/lo
  // moved out of this column, per hardware review. Source set per-refresh
  // in showDashboardScreen() from cur.condition.type via
  // bucketForCondition()/iconForBucket() - see weather_icon.h.
  g_conditionIcon = lv_image_create(infoBlock);
  lv_obj_set_size(g_conditionIcon, 130, 130);

  g_conditionLabel = makeLabel(infoBlock, kInk, &font_archivo_condition_26);
  lv_obj_set_width(g_conditionLabel, LV_PCT(100));
  lv_label_set_long_mode(g_conditionLabel, LV_LABEL_LONG_DOT);
  g_feelsLabel = makeLabel(infoBlock, kSub, &font_plexmono_feels_16);

  lv_obj_t *hilo = makeRow(infoBlock);
  lv_obj_set_style_pad_column(hilo, 14, 0);
  lv_obj_set_flex_align(hilo, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  g_hiLabel = makeLabel(hilo, kEmber, &font_plexmono_hilo_18);
  lv_obj_t *sep = makeLabel(hilo, kSub, &font_plexmono_hilo_18);
  lv_label_set_text(sep, "/");
  g_loLabel = makeLabel(hilo, kTeal, &font_plexmono_hilo_18);

  // 2x2, not the mockup's 1x4 - more room per cell within the same
  // overall width, which is what let the metric font sizes above grow.
  // Row height is LV_GRID_CONTENT (not FR(1)/stretch): the grid should
  // size to what its now-bigger cells actually need, with
  // buildPrimaryColumn()'s SPACE_BETWEEN taking up whatever's left
  // between it and the reading block above, not the other way around.
  static int32_t colDsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
  static int32_t rowDsc[] = {LV_GRID_CONTENT, LV_GRID_CONTENT, LV_GRID_TEMPLATE_LAST};
  lv_obj_t *metrics = lv_obj_create(col);
  lv_obj_set_size(metrics, LV_PCT(100), LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(metrics, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(metrics, 0, 0);
  lv_obj_set_style_pad_all(metrics, 0, 0);
  lv_obj_set_style_pad_column(metrics, 6, 0);
  lv_obj_set_style_pad_row(metrics, 6, 0);
  lv_obj_clear_flag(metrics, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_grid_dsc_array(metrics, colDsc, rowDsc);
  lv_obj_set_layout(metrics, LV_LAYOUT_GRID);

  const char *labels[4] = {"HUMIDITY", "WIND", "UV INDEX", "PRECIP"};
  for (size_t i = 0; i < 4; i++) {
    lv_obj_t *cell = buildMetricCell(metrics, labels[i], i);
    const int32_t column = static_cast<int32_t>(i % 2);
    const int32_t row = static_cast<int32_t>(i / 2);
    lv_obj_set_grid_cell(cell, LV_GRID_ALIGN_STRETCH, column, 1, LV_GRID_ALIGN_STRETCH, row, 1);
  }

  return col;
}

// ---------------------------------------------------------------------
// Daily column: "7-Day Outlook" title + up to 7 rows + footer.
// Mockup: .daily { padding: 20px 26px 16px }, .day-row { grid-template-
// columns: 74px 26px 1fr auto; gap: 12px; padding: 9px 0 } - the 26px
// icon column is dropped (no icons this phase), .range gap 8, .footer
// padding-top 10.
// ---------------------------------------------------------------------

DayRowWidgets buildDayRow(lv_obj_t *parent, bool isFirst) {
  DayRowWidgets w;
  w.row = makeRow(parent);
  // Sized by the parent grid's LV_GRID_ALIGN_STRETCH (see buildDailyColumn),
  // not LV_PCT/SIZE_CONTENT here - 7 rows stacked at their natural content
  // height silently overflowed past the footer once the section title grew
  // (LVGL flex doesn't shrink children to fit, unlike CSS flexbox), so each
  // row's height is now whatever an even 1/7th of the available space is,
  // guaranteed to fit regardless of title/font sizing elsewhere.
  lv_obj_set_style_pad_column(w.row, 12, 0);
  lv_obj_set_flex_align(w.row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  if (!isFirst) {
    lv_obj_set_style_border_side(w.row, LV_BORDER_SIDE_TOP, 0);
    lv_obj_set_style_border_color(w.row, lv_color_hex(kLine), 0);
    lv_obj_set_style_border_width(w.row, 1, 0);
  }

  w.name = makeLabel(w.row, kInk, &font_archivo_dayname_14);
  lv_obj_set_width(w.name, 74);

  // 26px - matches the mockup's .day-row .icon size (dashboard.html).
  // Source set per-refresh from day.daytimeCondition.type - see
  // showDashboardScreen(). DailyForecastPoint has no isDaytime, so this
  // is always the daytime bucket (never the Moon icon), same as the
  // mockup's own day-row icons.
  w.icon = lv_image_create(w.row);
  lv_obj_set_size(w.icon, 26, 26);

  lv_obj_t *range = makeRow(w.row);
  lv_obj_set_flex_grow(range, 1);
  lv_obj_set_style_pad_column(range, 8, 0);
  lv_obj_set_flex_align(range, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  w.lo = makeLabel(range, kTeal, &font_plexmono_dayrange_16);

  // 6px, not 3px - the grid-cell row height (see buildDailyColumn) leaves
  // plenty of vertical slack around this, center-aligned, per request.
  w.track = lv_obj_create(range);
  lv_obj_set_size(w.track, LV_PCT(100), 6);
  lv_obj_set_flex_grow(w.track, 1);
  lv_obj_set_style_bg_color(w.track, lv_color_hex(kLine), 0);
  lv_obj_set_style_bg_opa(w.track, LV_OPA_COVER, 0);
  lv_obj_set_style_border_width(w.track, 0, 0);
  lv_obj_set_style_radius(w.track, 3, 0);
  lv_obj_set_style_pad_all(w.track, 0, 0);
  lv_obj_clear_flag(w.track, LV_OBJ_FLAG_SCROLLABLE);

  w.fill = lv_obj_create(w.track);
  lv_obj_set_size(w.fill, 4, 6);
  lv_obj_set_style_bg_color(w.fill, lv_color_hex(kTeal), 0);
  lv_obj_set_style_bg_grad_color(w.fill, lv_color_hex(kEmber), 0);
  lv_obj_set_style_bg_grad_dir(w.fill, LV_GRAD_DIR_HOR, 0);
  lv_obj_set_style_bg_opa(w.fill, LV_OPA_COVER, 0);
  lv_obj_set_style_border_width(w.fill, 0, 0);
  lv_obj_set_style_radius(w.fill, 3, 0);
  lv_obj_clear_flag(w.fill, LV_OBJ_FLAG_SCROLLABLE);

  w.hi = makeLabel(range, kEmber, &font_plexmono_dayrange_16);

  w.pop = makeLabel(w.row, kSub, &font_plexmono_dailypop_11);
  lv_obj_set_width(w.pop, 34);
  lv_obj_set_style_text_align(w.pop, LV_TEXT_ALIGN_RIGHT, 0);

  return w;
}

void onDailyTitleClicked(lv_event_t *e) {
  LOG_D("ui", "daily title clicked, target=%p current_target=%p\n", static_cast<void *>(lv_event_get_target(e)),
        static_cast<void *>(lv_event_get_current_target(e)));
  showDailyForecastScreen(g_lastSnapshot);
  lv_screen_load(dailyForecastScreenObj());
}

lv_obj_t *buildDailyColumn(lv_obj_t *parent) {
  lv_obj_t *col = makeColumn(parent);
  lv_obj_set_height(col, LV_PCT(100));
  lv_obj_set_flex_grow(col, 100);
  lv_obj_set_style_pad_hor(col, 26, 0);
  lv_obj_set_style_pad_top(col, 20, 0);
  lv_obj_set_style_pad_bottom(col, 16, 0);

  // Same clickable-row + pill-button pattern as buildHourlyRow()'s
  // titleRow/expandBtn - the pill is its own clickable target (press
  // feedback scoped to it), titleRow stays clickable for taps elsewhere
  // in the row.
  lv_obj_t *titleRow = makeRow(col);
  lv_obj_set_width(titleRow, LV_PCT(100));
  lv_obj_set_style_pad_bottom(titleRow, 10, 0);
  lv_obj_set_flex_align(titleRow, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(titleRow, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_event_cb(titleRow, onDailyTitleClicked, LV_EVENT_CLICKED, nullptr);

  lv_obj_t *title = makeLabel(titleRow, kSub, &font_plexmono_dailytitle_22);
  lv_label_set_text(title, "7-DAY OUTLOOK");

  lv_obj_t *outlookBtn = lv_obj_create(titleRow);
  lv_obj_set_size(outlookBtn, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(outlookBtn, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_color(outlookBtn, lv_color_hex(kLineStrong), 0);
  lv_obj_set_style_border_width(outlookBtn, 1, 0);
  lv_obj_set_style_radius(outlookBtn, LV_RADIUS_CIRCLE, 0);
  lv_obj_set_style_pad_hor(outlookBtn, 12, 0);
  lv_obj_set_style_pad_ver(outlookBtn, 6, 0);
  lv_obj_clear_flag(outlookBtn, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_add_flag(outlookBtn, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_event_cb(outlookBtn, onDailyTitleClicked, LV_EVENT_CLICKED, nullptr);
  addPressFeedback(outlookBtn);
  lv_obj_t *outlook = makeLabel(outlookBtn, kSub, &font_plexmono_expand_22);
  lv_label_set_text(outlook, "Outlook ->");

  // Grid, not a flex column - kMaxDayRows (7) equal LV_GRID_FR(1) rows
  // guarantee every row fits within whatever height this section ends up
  // with, instead of stacking each row at its natural content height and
  // silently overflowing past the footer (LVGL flex has no CSS-flexbox-
  // style shrink-to-fit; confirmed on hardware once the title above grew).
  lv_obj_t *rows = lv_obj_create(col);
  lv_obj_set_size(rows, LV_PCT(100), LV_SIZE_CONTENT);
  lv_obj_set_flex_grow(rows, 1);
  lv_obj_set_style_bg_opa(rows, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(rows, 0, 0);
  lv_obj_set_style_pad_all(rows, 0, 0);
  lv_obj_clear_flag(rows, LV_OBJ_FLAG_SCROLLABLE);
  static int32_t rowsColDsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
  static int32_t rowsRowDsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1),
                                  LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
  static_assert(kMaxDayRows == 7, "rowsRowDsc above is hand-written for 7 rows");
  lv_obj_set_grid_dsc_array(rows, rowsColDsc, rowsRowDsc);
  lv_obj_set_layout(rows, LV_LAYOUT_GRID);
  for (size_t i = 0; i < kMaxDayRows; i++) {
    g_dayRows[i] = buildDayRow(rows, i == 0);
    lv_obj_set_grid_cell(g_dayRows[i].row, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_STRETCH,
                          static_cast<int32_t>(i), 1);
  }

  lv_obj_t *footer = makeRow(col);
  lv_obj_set_width(footer, LV_PCT(100));
  lv_obj_set_style_pad_top(footer, 10, 0);
  lv_obj_set_flex_align(footer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_t *source = makeLabel(footer, kSub, &font_plexmono_title_11);
  lv_label_set_text(source, "weather.googleapis.com");
  lv_obj_t *version = makeLabel(footer, kSub, &font_plexmono_title_11);
  lv_label_set_text(version, "v1 · forecast.days");

  return col;
}

// ---------------------------------------------------------------------
// Hourly strip: title + up to 8 bar-chart columns.
// Mockup: .hourly { padding: 14px 30px 16px }, .head margin-bottom 8,
// .hourly-row gap 4, .hour gap 6 / padding-top 6, .bar-wrap height 46,
// .bar width 4.
// ---------------------------------------------------------------------

// 56/6px, not 46/4px - each of the 8 columns has ~150px of width to work
// with (1220px content width / 8), far more than a 4px bar needed, per
// hardware review of the hourly strip's readability.
constexpr int32_t kBarWrapHeight = 56;
constexpr int32_t kBarWidth = 6;

HourCellWidgets buildHourCell(lv_obj_t *parent) {
  HourCellWidgets w;
  w.cell = makeColumn(parent);
  lv_obj_set_flex_align(w.cell, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_set_style_pad_row(w.cell, 7, 0);
  lv_obj_set_style_pad_top(w.cell, 7, 0);

  w.t = makeLabel(w.cell, kSub, &font_plexmono_hourclock_16);

  w.barWrap = lv_obj_create(w.cell);
  lv_obj_set_size(w.barWrap, kBarWidth, kBarWrapHeight);
  lv_obj_set_style_bg_opa(w.barWrap, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(w.barWrap, 0, 0);
  lv_obj_set_style_pad_all(w.barWrap, 0, 0);
  lv_obj_clear_flag(w.barWrap, LV_OBJ_FLAG_SCROLLABLE);

  w.bar = lv_obj_create(w.barWrap);
  lv_obj_set_size(w.bar, kBarWidth, 1);
  lv_obj_align(w.bar, LV_ALIGN_BOTTOM_MID, 0, 0);
  lv_obj_set_style_bg_color(w.bar, lv_color_hex(kBrass), 0);
  lv_obj_set_style_bg_opa(w.bar, LV_OPA_COVER, 0);
  lv_obj_set_style_border_width(w.bar, 0, 0);
  lv_obj_set_style_radius(w.bar, 3, 0);
  lv_obj_clear_flag(w.bar, LV_OBJ_FLAG_SCROLLABLE);

  w.temp = makeLabel(w.cell, kInk, &font_plexmono_hourtemp_20);
  w.pop = makeLabel(w.cell, kTeal, &font_plexmono_hourpop_14);

  return w;
}

void onHourlyTitleClicked(lv_event_t *e) {
  LOG_D("ui", "hourly title clicked, target=%p current_target=%p\n", static_cast<void *>(lv_event_get_target(e)),
        static_cast<void *>(lv_event_get_current_target(e)));
  showHourlyDetailScreen(g_lastSnapshot);
  lv_screen_load(hourlyDetailScreenObj());
}

lv_obj_t *buildHourlyRow(lv_obj_t *parent) {
  lv_obj_t *section = makeColumn(parent);
  lv_obj_set_width(section, LV_PCT(100));
  lv_obj_set_style_pad_hor(section, 30, 0);
  lv_obj_set_style_pad_top(section, 14, 0);
  lv_obj_set_style_pad_bottom(section, 16, 0);
  lv_obj_set_style_border_side(section, LV_BORDER_SIDE_TOP, 0);
  lv_obj_set_style_border_color(section, lv_color_hex(kLine), 0);
  lv_obj_set_style_border_width(section, 1, 0);

  // Whole row is the tap target (not just the small "EXPAND" text) -
  // a bigger touch target matters more on a kiosk panel than matching
  // the mockup's plain <a> hyperlink literally.
  lv_obj_t *titleRow = makeRow(section);
  lv_obj_set_width(titleRow, LV_PCT(100));
  lv_obj_set_style_pad_bottom(titleRow, 8, 0);
  lv_obj_set_flex_align(titleRow, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(titleRow, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_event_cb(titleRow, onHourlyTitleClicked, LV_EVENT_CLICKED, nullptr);

  lv_obj_t *title = makeLabel(titleRow, kSub, &font_plexmono_hourlytitle_16);
  lv_label_set_text(title, "HOURLY · NEXT 8 HOURS");

  // Pill-bordered button, matching hourly_detail_ui.cpp's "<- Dashboard"
  // back button styling exactly (same border color/width, radius,
  // padding) per request - the whole titleRow stays the actual tap
  // target (see the comment above), this is just visual.
  lv_obj_t *expandBtn = lv_obj_create(titleRow);
  lv_obj_set_size(expandBtn, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(expandBtn, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_color(expandBtn, lv_color_hex(kLineStrong), 0);
  lv_obj_set_style_border_width(expandBtn, 1, 0);
  lv_obj_set_style_radius(expandBtn, LV_RADIUS_CIRCLE, 0);
  lv_obj_set_style_pad_hor(expandBtn, 12, 0);
  lv_obj_set_style_pad_ver(expandBtn, 6, 0);
  lv_obj_clear_flag(expandBtn, LV_OBJ_FLAG_SCROLLABLE);
  // Its own clickable target (not just relying on titleRow's), so the
  // press-feedback highlight below is scoped to the pill itself rather
  // than the whole row - titleRow stays clickable too, for taps that
  // land elsewhere in the row (e.g. on the "HOURLY..." label).
  lv_obj_add_flag(expandBtn, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_event_cb(expandBtn, onHourlyTitleClicked, LV_EVENT_CLICKED, nullptr);
  addPressFeedback(expandBtn);
  lv_obj_t *expand = makeLabel(expandBtn, kSub, &font_plexmono_expand_22);
  lv_label_set_text(expand, "Expand ->");

  static int32_t colDsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1),
                              LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1),
                              LV_GRID_TEMPLATE_LAST};
  static int32_t rowDsc[] = {LV_GRID_CONTENT, LV_GRID_TEMPLATE_LAST};
  lv_obj_t *grid = lv_obj_create(section);
  lv_obj_set_size(grid, LV_PCT(100), LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(grid, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(grid, 0, 0);
  lv_obj_set_style_pad_all(grid, 0, 0);
  lv_obj_set_style_pad_column(grid, 8, 0);
  lv_obj_clear_flag(grid, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_grid_dsc_array(grid, colDsc, rowDsc);
  lv_obj_set_layout(grid, LV_LAYOUT_GRID);

  for (size_t i = 0; i < kMaxHourCells; i++) {
    g_hourCells[i] = buildHourCell(grid);
    lv_obj_set_grid_cell(g_hourCells[i].cell, LV_GRID_ALIGN_STRETCH, static_cast<int32_t>(i), 1, LV_GRID_ALIGN_STRETCH,
                          0, 1);
  }

  return section;
}

void buildScreen() {
  g_screen = lv_obj_create(nullptr);
  lv_obj_set_style_bg_color(g_screen, lv_color_hex(kPaper), 0);
  lv_obj_set_style_bg_opa(g_screen, LV_OPA_COVER, 0);
  lv_obj_set_style_pad_all(g_screen, 0, 0);
  lv_obj_set_style_border_width(g_screen, 0, 0);
  lv_obj_set_flex_flow(g_screen, LV_FLEX_FLOW_COLUMN);
  lv_obj_clear_flag(g_screen, LV_OBJ_FLAG_SCROLLABLE);

  buildStatusbar(g_screen);

  lv_obj_t *mainRow = lv_obj_create(g_screen);
  lv_obj_set_width(mainRow, LV_PCT(100));
  // Grows to fill whatever's left between the statusbar and the hourly
  // strip below (both content-sized), not LV_SIZE_CONTENT - the
  // primary/daily columns inside size themselves to LV_PCT(100) of
  // *this* row's height, which is circular (and resolves to ~zero) if
  // this row is itself only as tall as its content. Confirmed on
  // hardware: without this, the row collapsed to just its own 1px
  // border, and the entire primary/daily section silently disappeared.
  lv_obj_set_flex_grow(mainRow, 1);
  lv_obj_set_style_bg_opa(mainRow, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_side(mainRow, LV_BORDER_SIDE_TOP, 0);
  lv_obj_set_style_border_color(mainRow, lv_color_hex(kLine), 0);
  lv_obj_set_style_border_width(mainRow, 1, 0);
  lv_obj_set_style_pad_all(mainRow, 0, 0);
  lv_obj_set_flex_flow(mainRow, LV_FLEX_FLOW_ROW);
  lv_obj_clear_flag(mainRow, LV_OBJ_FLAG_SCROLLABLE);

  buildPrimaryColumn(mainRow);
  buildDailyColumn(mainRow);

  buildHourlyRow(g_screen);

  lv_screen_load(g_screen);
}

// currentTime is a full RFC3339 timestamp (e.g.
// "2024-05-13T21:53:24.752338756Z") - just what's needed for "AS OF
// HH:MM" is the 5 characters right after 'T', no full datetime parse.
String extractHhMm(const String &rfc3339) {
  int t = rfc3339.indexOf('T');
  if (t < 0 || rfc3339.length() < static_cast<unsigned>(t) + 6) {
    return "--:--";
  }
  return rfc3339.substring(t + 1, t + 6);
}

// Weather API's wind.direction.cardinal is one of the 16 compass points
// spelled out in full (e.g. "EAST_NORTHEAST"), not an abbreviation - too
// long for the metric grid's width. Maps to the standard 1-3 letter
// abbreviation; falls back to the raw value (better than blank) if
// Google ever adds a point this table doesn't have yet.
const char *abbreviateCardinal(const String &cardinal) {
  struct Entry {
    const char *full;
    const char *abbr;
  };
  static const Entry kEntries[] = {
      {"NORTH", "N"},           {"NORTH_NORTHEAST", "NNE"}, {"NORTHEAST", "NE"}, {"EAST_NORTHEAST", "ENE"},
      {"EAST", "E"},            {"EAST_SOUTHEAST", "ESE"},  {"SOUTHEAST", "SE"}, {"SOUTH_SOUTHEAST", "SSE"},
      {"SOUTH", "S"},           {"SOUTH_SOUTHWEST", "SSW"}, {"SOUTHWEST", "SW"}, {"WEST_SOUTHWEST", "WSW"},
      {"WEST", "W"},            {"WEST_NORTHWEST", "WNW"},  {"NORTHWEST", "NW"}, {"NORTH_NORTHWEST", "NNW"},
  };
  for (const Entry &entry : kEntries) {
    if (cardinal == entry.full) {
      return entry.abbr;
    }
  }
  return cardinal.c_str();
}

// Shared 3-bucket "value -> instrument-panel accent" mapping for metrics
// with a genuine ascending risk/severity gradient (UV index, precip
// chance) - not applied to every metric: humidity's "notable at both
// extremes, fine in the middle" shape doesn't fit an ascending scale,
// and typical wind speeds rarely reach anything worth flagging, so
// those stay neutral (kSub/kInk) rather than forcing this pattern onto
// values it doesn't describe well.
uint32_t severityColor(float value, float moderateThreshold, float highThreshold) {
  return value >= highThreshold ? kEmber : value >= moderateThreshold ? kBrass : kTeal;
}

}  // namespace

void showDashboardScreen(const SharedState::DashboardSnapshot &data) {
  g_lastSnapshot = data;

  const bool firstBuild = (g_screen == nullptr);
  if (firstBuild) {
    buildScreen();
    // LV_MEM_SIZE usage right after this screen's own object tree is
    // built - see that constant's own comment (lv_conf.h) for why this
    // is being watched (a real hardware watchdog crash inside LVGL's
    // draw code, first seen once all three screens were simultaneously
    // resident).
    lv_mem_monitor_t mon;
    lv_mem_monitor(&mon);
    LOG_D("ui", "lv mem after dashboard build: used=%u%% frag=%u%% free=%u\n", mon.used_pct, mon.frag_pct,
          static_cast<unsigned>(mon.free_size));
  }
  LOG_D("ui", "showDashboardScreen called, firstBuild=%d screen=%p\n", firstBuild, static_cast<void *>(g_screen));

  // Location text is fixed once resolved (never changes mid-session) -
  // setting it on every call is wasted work, but cheap enough (two
  // label-text-set calls) that a separate "first call only" path isn't
  // worth the extra state. displayLocation is the resolved "City, ST"
  // when available, already computed in main.cpp's
  // fetchDashboardSnapshot() - this file doesn't need to know it might
  // instead be a raw ZIP code some of the time.
  lv_label_set_text(g_nameLabel, data.displayLocation.c_str());
  lv_label_set_text(g_regionLabel, "GOOGLE WEATHER");

  const char *degText = data.unitsImperial ? "°F" : "°C";

  const CurrentConditions &cur = data.current;

  char tempBuf[8];
  snprintf(tempBuf, sizeof(tempBuf), "%d", static_cast<int>(cur.temperature));
  lv_label_set_text(g_tempLabel, tempBuf);
  lv_label_set_text(g_degLabel, degText);

  lv_label_set_text(g_conditionLabel, cur.condition.description.c_str());
  lv_image_set_src(g_conditionIcon,
                    iconForBucket(bucketForCondition(cur.condition.type.c_str(), cur.isDaytime), IconSize::Hero));

  char feelsBuf[64];
  snprintf(feelsBuf, sizeof(feelsBuf), "FEELS LIKE %d° · AS OF %s", static_cast<int>(cur.feelsLikeTemperature),
            extractHhMm(cur.currentTime).c_str());
  lv_label_set_text(g_feelsLabel, feelsBuf);

  char hiBuf[24];
  char loBuf[24];
  float hiTemp = cur.temperature;
  float loTemp = cur.temperature;
  if (data.dailyCount > 0) {
    hiTemp = data.daily[0].maxTemperature;
    loTemp = data.daily[0].minTemperature;
  }
  snprintf(hiBuf, sizeof(hiBuf), "↑%d° HIGH", static_cast<int>(hiTemp));
  snprintf(loBuf, sizeof(loBuf), "↓%d° LOW", static_cast<int>(loTemp));
  lv_label_set_text(g_hiLabel, hiBuf);
  lv_label_set_text(g_loLabel, loBuf);

  char humidityBuf[8];
  snprintf(humidityBuf, sizeof(humidityBuf), "%d", cur.relativeHumidity);
  lv_label_set_text(g_metricValueLabels[0], humidityBuf);
  lv_label_set_text(g_metricSpanLabels[0], "%");

  char windBuf[8];
  snprintf(windBuf, sizeof(windBuf), "%d", static_cast<int>(cur.windSpeed));
  lv_label_set_text(g_metricValueLabels[1], windBuf);
  char windSpanBuf[24];
  snprintf(windSpanBuf, sizeof(windSpanBuf), " mph %s", abbreviateCardinal(cur.windDirectionCardinal));
  lv_label_set_text(g_metricSpanLabels[1], windSpanBuf);

  char uvBuf[8];
  snprintf(uvBuf, sizeof(uvBuf), "%d", static_cast<int>(cur.uvIndex));
  lv_label_set_text(g_metricValueLabels[2], uvBuf);
  const char *uvWord = cur.uvIndex >= 8   ? "very high"
                       : cur.uvIndex >= 6 ? "high"
                       : cur.uvIndex >= 3 ? "moderate"
                                          : "low";
  lv_label_set_text(g_metricSpanLabels[2], uvWord);
  // UV and precip get colored (both a real ascending risk gradient) -
  // reuses the existing instrument-panel accents rather than
  // introducing a new hazard-scale palette, same reasoning as hi/lo
  // temperature already sharing these two colors. Humidity/wind stay
  // neutral - see severityColor()'s comment for why. High/very high (UV)
  // and >=50%/moderate (precip) share ember/brass respectively (only
  // two colors past "low" to work with); the word/number still
  // distinguishes the two ends where it matters (UV's word text).
  const uint32_t uvColor = severityColor(cur.uvIndex, 3, 6);
  lv_obj_set_style_text_color(g_metricValueLabels[2], lv_color_hex(uvColor), 0);
  lv_obj_set_style_text_color(g_metricSpanLabels[2], lv_color_hex(uvColor), 0);

  char precipBuf[8];
  snprintf(precipBuf, sizeof(precipBuf), "%d", cur.precipitationProbabilityPercent);
  lv_label_set_text(g_metricValueLabels[3], precipBuf);
  lv_label_set_text(g_metricSpanLabels[3], "%");
  const uint32_t precipColor = severityColor(static_cast<float>(cur.precipitationProbabilityPercent), 20, 50);
  lv_obj_set_style_text_color(g_metricValueLabels[3], lv_color_hex(precipColor), 0);
  lv_obj_set_style_text_color(g_metricSpanLabels[3], lv_color_hex(precipColor), 0);

  // Daily rows: render up to what actually came back (<= kMaxDailyPoints),
  // hide the rest rather than showing empty rows.
  float dayMin = 1e9f;
  float dayMax = -1e9f;
  for (size_t i = 0; i < data.dailyCount; i++) {
    dayMin = min(dayMin, data.daily[i].minTemperature);
    dayMax = max(dayMax, data.daily[i].maxTemperature);
  }
  const float dayRange = (dayMax > dayMin) ? (dayMax - dayMin) : 1.0f;

  for (size_t i = 0; i < kMaxDayRows; i++) {
    DayRowWidgets &w = g_dayRows[i];
    if (i >= data.dailyCount) {
      lv_obj_add_flag(w.row, LV_OBJ_FLAG_HIDDEN);
      continue;
    }
    lv_obj_clear_flag(w.row, LV_OBJ_FLAG_HIDDEN);

    const DailyForecastPoint &day = data.daily[i];
    if (i == 0) {
      lv_label_set_text(w.name, "Today");
      lv_obj_set_style_text_color(w.name, lv_color_hex(kBrassStrong), 0);
    } else if (i == 1) {
      lv_label_set_text(w.name, "Tomorrow");
      lv_obj_set_style_text_color(w.name, lv_color_hex(kInk), 0);
    } else {
      const int weekday = weekdayFromIsoDate(day.displayDate);
      // Falls back to the raw "YYYY-MM-DD" if the API ever sends a
      // malformed date - still shows something rather than nothing.
      lv_label_set_text(w.name, weekday >= 0 ? weekdayAbbrev(weekday) : day.displayDate.c_str());
      lv_obj_set_style_text_color(w.name, lv_color_hex(kInk), 0);
    }

    lv_image_set_src(w.icon, iconForBucket(bucketForCondition(day.daytimeCondition.type.c_str(), /*isDaytime=*/true),
                                            IconSize::DayRow));

    char loBuf2[8];
    char hiBuf2[8];
    snprintf(loBuf2, sizeof(loBuf2), "%d°", static_cast<int>(day.minTemperature));
    snprintf(hiBuf2, sizeof(hiBuf2), "%d°", static_cast<int>(day.maxTemperature));
    lv_label_set_text(w.lo, loBuf2);
    lv_label_set_text(w.hi, hiBuf2);

    // Forces LVGL to resolve the flex layout for the tree built above
    // before reading geometry from it - without this, lv_obj_get_width()
    // on a track that was just created this same call (the first-ever
    // showDashboardScreen(), right after buildScreen()) still returns 0,
    // since flex sizing is otherwise only resolved on the next
    // lv_timer_handler() pass. That silently skipped the trackWidth > 0
    // branch below, leaving that day's fill bar at its default
    // (invisible) size for good - the intermittent "doesn't populate"
    // symptom, not a data problem.
    lv_obj_update_layout(w.track);
    const int32_t trackWidth = lv_obj_get_width(w.track);
    if (trackWidth > 0) {
      const int32_t left =
          static_cast<int32_t>(((day.minTemperature - dayMin) / dayRange) * static_cast<float>(trackWidth));
      const int32_t width = static_cast<int32_t>(
          ((day.maxTemperature - day.minTemperature) / dayRange) * static_cast<float>(trackWidth));
      lv_obj_set_x(w.fill, left);
      lv_obj_set_width(w.fill, width < 3 ? 3 : width);
    }

    char popBuf[8];
    snprintf(popBuf, sizeof(popBuf), "%d%%", day.precipitationProbabilityPercent);
    lv_label_set_text(w.pop, popBuf);
  }

  // Hourly bars: same min/max-normalize-to-height approach as the mockup's
  // own JS.
  float hourMin = 1e9f;
  float hourMax = -1e9f;
  for (size_t i = 0; i < data.hourlyCount; i++) {
    hourMin = min(hourMin, data.hourly[i].temperature);
    hourMax = max(hourMax, data.hourly[i].temperature);
  }
  const float hourRange = (hourMax > hourMin) ? (hourMax - hourMin) : 1.0f;

  for (size_t i = 0; i < kMaxHourCells; i++) {
    HourCellWidgets &w = g_hourCells[i];
    if (i >= data.hourlyCount) {
      lv_obj_add_flag(w.cell, LV_OBJ_FLAG_HIDDEN);
      continue;
    }
    lv_obj_clear_flag(w.cell, LV_OBJ_FLAG_HIDDEN);

    const HourlyForecastPoint &hour = data.hourly[i];
    // Relative to now ("+1Hr", "+2Hr", ...) rather than the raw API hour
    // number - reads at a glance without needing 12/24hr formatting, per
    // request. Index-derived (each entry is exactly one hour after the
    // last - see weather.cpp's forecastHours fetch), not parsed from
    // hour.displayDateTime.
    if (i == 0) {
      lv_label_set_text(w.t, "NOW");
    } else {
      char hourOffsetBuf[8];
      snprintf(hourOffsetBuf, sizeof(hourOffsetBuf), "+%uHr", static_cast<unsigned>(i));
      lv_label_set_text(w.t, hourOffsetBuf);
    }

    const float pct = 0.18f + ((hour.temperature - hourMin) / hourRange) * 0.82f;
    const int32_t barHeight = static_cast<int32_t>(pct * static_cast<float>(kBarWrapHeight));
    lv_obj_set_height(w.bar, barHeight < 1 ? 1 : barHeight);
    lv_obj_set_style_bg_color(w.bar, lv_color_hex(i == 0 ? kBrassStrong : kBrass), 0);

    char hourTempBuf[8];
    snprintf(hourTempBuf, sizeof(hourTempBuf), "%d°", static_cast<int>(hour.temperature));
    lv_label_set_text(w.temp, hourTempBuf);

    if (hour.precipitationProbabilityPercent >= 20) {
      char hourPopBuf[8];
      snprintf(hourPopBuf, sizeof(hourPopBuf), "%d%%", hour.precipitationProbabilityPercent);
      lv_label_set_text(w.pop, hourPopBuf);
    } else {
      lv_label_set_text(w.pop, "");
    }
  }

  refreshDashboardClock(data);
}

void refreshDashboardClock(const SharedState::DashboardSnapshot &data) {
  if (g_screen == nullptr) {
    return;
  }

  const time_t now = time(nullptr);

  // data.utcOffsetSec (raw + DST, from the Time Zone API - see
  // timezone_lookup.h) is added to the UTC epoch here rather than via the
  // system TZ/NTP config (setenv("TZ",...)/configTime()): the offset can
  // arrive well after boot (it depends on a network lookup that runs
  // after WiFi/geocoding), and re-touching NTP config after the fact
  // risks a disruptive resync of an already-correct clock for no
  // benefit. gmtime_r() on a pre-shifted epoch gives correct wall-clock
  // fields without any of that - defaults to UTC (offset 0) until
  // resolveTimezoneIfNeeded() (main.cpp) succeeds, same as before this
  // existed.
  const time_t localNow = now + data.utcOffsetSec;
  struct tm tmInfo;
  gmtime_r(&localNow, &tmInfo);
  char clockBuf[6];
  snprintf(clockBuf, sizeof(clockBuf), "%02d:%02d", tmInfo.tm_hour, tmInfo.tm_min);
  lv_label_set_text(g_clockLabel, clockBuf);

  char syncBuf[32];
  if (data.syncedAtUnix <= 0) {
    snprintf(syncBuf, sizeof(syncBuf), "Not yet synced");
  } else {
    // Both sides are UTC (unshifted) - a duration, so the offset would
    // cancel out anyway, but using `now` here instead of `localNow` keeps
    // that obviously true rather than relying on the cancellation.
    const long ageSec = static_cast<long>(now - data.syncedAtUnix);
    const long ageMin = ageSec / 60;
    if (ageMin < 1) {
      snprintf(syncBuf, sizeof(syncBuf), "Synced just now");
    } else {
      snprintf(syncBuf, sizeof(syncBuf), "Synced %ldm ago", ageMin);
    }
  }
  lv_label_set_text(g_syncLabel, syncBuf);
}

lv_obj_t *dashboardScreenObj() { return g_screen; }
